[package]
name = "avro"
version = "0.1.0"
authors = ["Jordan Miner <jminer7@gmail.com>"]
description = "A Rust implementation of Apache Avro"
repository = "https://github.com/jminer/rust-avro"
license = "Apache-2.0/MIT"
readme = "README.md"

[dependencies]
serde_json = "0.6"
